{% set name = "napari-tracks-reader" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-tracks-reader-{{ version }}.tar.gz
  sha256: 1584f8f805e96f6c94d8f40384203cc327917afb76e4291acf624b120f9ccfa1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - napari-plugin-engine >=0.1.4
    - numpy
    - pandas >=1.2.4
    - python >={{ python_min }}

test:
  imports:
    - napari_tracks_reader
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sylvainprigent/napari-tracks-reader
  summary: Read tracks from txt (xml, csv) files to napari
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
